language: ruby
rvm:
  - 2.1
sudo: required
before_install:
  - curl -s http://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/xamarin.list
  - sudo apt-get update -y
  - sudo apt-get install -y mono-complete
  - mono --version
  - curl -O -L https://www.nuget.org/nuget.exe
  - mono nuget.exe  
script:
  - "bundle exec jekyll build --safe"
  - mono nuget.exe install RhinoCommon -source https://pyget.herokuapp.com/
  - cp RhinoCommon*/lib/RhinoCommon.dll .
  - ruby test/compile-sample.rb _samples/rhinocommon/meshvolume.md
branches:
  only:
    - gh-pages
    - /pages-(.*)/ # test every branch which starts with "pages-"
